name: ecommerce-catalog

services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:admin@db/postgres
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET=ecommerce-catalog
      - AWS_ENDPOINT_URL=http://minio:9000
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.postgres
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=0
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin.servers.json:/pgadmin4/servers.json
    ports:
      - 8070:80

  minio:
    image: minio/minio
    
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data

volumes:
  db-data:
  pgadmin-data:
  minio_storage: