name: ecommerce-catalog

services:
  app:
    build:
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ../.:/home/node/workspace
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.postgres
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=0
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin.servers.json:/pgadmin4/servers.json
    ports:
      - 8070:80

volumes:
  db-data:
  pgadmin-data: